name: onda_ritmica
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Yaahowu
      fonts:
        - asset: assets/fonts/Yaahowu_Light.ttf
          weight: 300
        - asset: assets/fonts/Yaahowu.ttf
          weight: 400
        - asset: assets/fonts/Yaahowu_Bold.ttf
          weight: 700
        - asset: assets/fonts/Yaahowu_Thick.ttf
          weight: 800